### ISSUE TITLE
Bug - "No active speech found in audio results"

### ISSUE THREAD

**Issue by eschmidbauer** [mobiusml/faster-whisper#35]
im experiencing this issue: https://github.com/SYSTRAN/faster-whisper/issues/997 in your code base
The PR [here](https://github.com/SYSTRAN/faster-whisper/pull/936) resolves it. 
Since your code now supports turbo - would you be able to pick the code from this [PR](https://github.com/SYSTRAN/faster-whisper/pull/936) to solve the issue?

**Comment by Jiltseb** [comment]
Could you tell me more about the issue?  Do you have an open Issue in the SYSTRAN version? Once I get clarity on the issue, I will definitely look into it. Thanks.

**Comment by eschmidbauer** [comment]
getting this exception: 
```stack expects a non-empty TensorList```

**Comment by Jiltseb** [comment]
On it
